/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LinkButton: typeof import('./../components/Menu/LinkButton.vue')['default']
    MenuHiddenLinksWidget: typeof import('./../components/Menu/MenuHiddenLinksWidget.vue')['default']
    MenuLinkButton: typeof import('./../components/Menu/MenuLinkButton.vue')['default']
    PagesContentEditor: typeof import('./../components/Pages/PagesContentEditor.vue')['default']
    PagesContentEditorModelSelect: typeof import('./../components/Pages/PagesContentEditorModelSelect.vue')['default']
    PagesTable: typeof import('./../components/Pages/PagesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheConfirm: typeof import('./../components/TheConfirm.vue')['default']
    TheNavigation: typeof import('./../components/TheNavigation.vue')['default']
    TheSettings: typeof import('./../components/TheSettings.vue')['default']
    TheThemeToggle: typeof import('./../components/TheThemeToggle.vue')['default']
    TheToasts: typeof import('./../components/TheToasts.vue')['default']
    VButton: typeof import('./../components/V/VButton.vue')['default']
    VDialog: typeof import('./../components/V/VDialog.vue')['default']
    VEditor: typeof import('./../components/V/VEditor.vue')['default']
    VInput: typeof import('./../components/V/VInput.vue')['default']
    VLoading: typeof import('./../components/V/VLoading.vue')['default']
    VSelect: typeof import('./../components/V/VSelect.vue')['default']
  }
}
