/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FilesDirItem: typeof import('./../components/Files/FilesDirItem.vue')['default']
    FilesFileItem: typeof import('./../components/Files/FilesFileItem.vue')['default']
    FooterRow: typeof import('./../components/Footer/FooterRow.vue')['default']
    FooterRowActionSelect: typeof import('./../components/Footer/FooterRowActionSelect.vue')['default']
    IconsSnippetDoubleContainer: typeof import('./../components/Icons/IconsSnippetDoubleContainer.vue')['default']
    IconsSnippetIndentedParagraphs: typeof import('./../components/Icons/IconsSnippetIndentedParagraphs.vue')['default']
    IconsSnippetTripleContainer: typeof import('./../components/Icons/IconsSnippetTripleContainer.vue')['default']
    IconsSnippetUnorderedList: typeof import('./../components/Icons/IconsSnippetUnorderedList.vue')['default']
    LanguageSelect: typeof import('./../components/LanguageSelect.vue')['default']
    MenuHiddenLinksWidget: typeof import('./../components/Menu/MenuHiddenLinksWidget.vue')['default']
    MenuLinkButton: typeof import('./../components/Menu/MenuLinkButton.vue')['default']
    PagesContentEditor: typeof import('./../components/Pages/PagesContentEditor.vue')['default']
    PagesContentEditorModelSelect: typeof import('./../components/Pages/PagesContentEditorModelSelect.vue')['default']
    PagesFilesDialog: typeof import('./../components/Pages/PagesFilesDialog.vue')['default']
    PagesSnippetsDialog: typeof import('./../components/Pages/PagesSnippetsDialog.vue')['default']
    PagesTable: typeof import('./../components/Pages/PagesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavigation: typeof import('./../components/TheNavigation.vue')['default']
    TheSettings: typeof import('./../components/TheSettings.vue')['default']
    TheSlider: typeof import('./../components/TheSlider.vue')['default']
    TheThemeToggle: typeof import('./../components/TheThemeToggle.vue')['default']
    TheToasts: typeof import('./../components/TheToasts.vue')['default']
    VAlert: typeof import('./../components/V/VAlert.vue')['default']
    VButton: typeof import('./../components/V/VButton.vue')['default']
    VCombobox: typeof import('./../components/V/VCombobox.vue')['default']
    VDialog: typeof import('./../components/V/VDialog.vue')['default']
    VEditor: typeof import('./../components/V/VEditor.vue')['default']
    VInput: typeof import('./../components/V/VInput.vue')['default']
    VLoading: typeof import('./../components/V/VLoading.vue')['default']
    VSwitch: typeof import('./../components/V/VSwitch.vue')['default']
  }
}
